### ISSUE TITLE
[SpiritualGifts] Call to GlobalAttributesCache.GetMergeFields is obsolete

### ISSUE THREAD

**Issue by dcs619** [CentralAZ/Rockit-CentralAZ#3]
In the latest [pre-alpha-release](https://github.com/SparkDevNetwork/Rock/tree/pre-alpha-release) branch, [SpiritualGiftsTest](https://github.com/CentralAZ/Rockit-CentralAZ/blob/develop/RockWeb/Plugins/com_centralaz/SpiritualGifts/SpiritualGiftTest.ascx.cs#L303) is throwing `GetMergeFields is obsolete: use Rock.Lava.LavaHelper.GetCommonMergeFields instead`.

**Comment by nairdo** [comment]
Thanks for letting us know about this old repo :)  Taylor fixed this in our real repo (Rock-CentralAZ).  We're going to blow this old one away in a few days.
